server:
  port: 8088
spring:
  shardingsphere:
    datasource:
      common:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        username: repl
      ds-0:
        jdbc-url: jdbc:mysql://localhost:3316/ms_test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
      ds-1:
        jdbc-url: jdbc:mysql://localhost:3317/ms_test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
      ds-2:
        jdbc-url: jdbc:mysql://localhost:3318/ms_test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
      ds-3:
        jdbc-url: jdbc:mysql://localhost:3319/ms_test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
      names: ds-0,ds-1,ds-2,ds-3
    props:
      sql-show: true
    rules:
      replica-query:
        data-sources:
          pr_ds:
            primary-data-source-name: ds-0
            replica-data-source-names: ds-1,ds-2,ds-3
        load-balancers:
          round-robin:
            props:
              workid: 123
            type: ROUND_ROBIN